site_name: '我的 Angular 課程筆記'
site_dir: public
site_url: http://127.0.0.1:8000
# repo_url: Github, Gitlab...

nav:
  - Home:
    - Angular 簡介: index.md
    - 安裝相關工具: home/install.md
    - 常用 CLI指令: home/cli.md

  - 路由與導覽列:
    - 什麼是Route: route/route.md
    - 導覽列樣式: route/navstyle.md
    - 參數的傳遞: route/routerparam.md

  - 各種組件:
        元件 Component:    
            什麼是元件: component/component.md
            元件的生命週期: component/lifecycle.md
            ng-content: component/ngcontent.md
            # Input, Ouput: route/route.md
        # 指令 Directive:    
        #     什麼是Angular的元件: route/route.md
        # 管道 Pipe:    
        #     什麼是Angular的元件: route/route.md
        # 服務 Service:    
        #     依存注入 DI: route/route.md
        #     HttpClient: route/route.md
  

  - Part1:
    - 安裝: part1/ch01.md
    - MVC: part1/ch02.md
    
  - Part2:
    - 第一章: part2/ch01.md
    - 第二章: part2/ch02.md



theme:
  palette:
      # scheme: slate
      # primary: black
  name: material
  logo: assets/angular_logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top



plugins:
  - search:
      lang: ja 

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  